name: tests

on: [push]

jobs:
  build:
    runs-on: self-hosted
    container:
      image: docker://lorenzetti/lorenzetti:latest
      volumes: 
        - volume:/volume

    steps:
      - name: Compile
        shell: bash
        run: source /setup_envs.sh
              
