name: tests

on: [push]

jobs:

  workdir:
    runs-on: self-hosted
    container:
      image: docker://lorenzetti/lorenzetti:latest
    steps:
      - name: Workdir
        shell: bash
        run: |
          export GIT_RUNNER_BASEPATH=$pwd
          rm -rf *
          git clone https://github.com/lorenzetti-hep/lorenzetti.git

  build:
    runs-on: self-hosted
    needs: workdir
    container:
      image: docker://lorenzetti/lorenzetti:latest
    steps:
      - name: Compile
        shell: bash
        run: |
          export GIT_RUNNER_BASEPATH=$pwd
          export CPU_N=$(grep -c ^processor /proc/cpuinfo)
          source /setup_envs.sh
          cd lorenzetti && mkdir build && cd build && cmake .. && make -j$CPU_N && cd ..
          source setup.sh
          

          
  main_generation:
    runs-on: self-hosted
    needs: build
    container:
      image: docker://lorenzetti/lorenzetti:latest
    steps:
      - name: Generation
        shell: bash
        run: |
          export REPO_TESTS=$pwd/lorenzetti/tests
          source /setup_envs.sh && cd lorenzetti && source setup.sh
          echo $REPO_TESTS
          cd $REPO_TESTS
          source test_main_generation.sh




              
