name: tests

on: [push]

jobs:
  build:
    runs-on: self-hosted
    container:
      image: docker://lorenzetti/lorenzetti:latest
      volumes: 
        - volume:/voume

    steps:
      - name: Compile
        run: source /setup_envs.sh
              
