name: tests

on: [push]

jobs:
  build:
    runs-on: self-hosted
    container:
      image: docker://lorenzetti/lorenzetti:latest
      volumes: 
        - volume:/volume

    steps:
      - name: Compile
        shell: bash
        run: source /setup_envs.sh && cd /volume && cd git clone https://github.com/lorenzetti-hep/lorenzetti.git && \
             cd lorenzetti && mkdir build && cd build && cmake .. && make -j8 && cd .. && source setup_here.sh
              
