name: tests

on: [push]

jobs:

  workdir:
    runs-on: self-hosted
    container:
      image: docker://lorenzetti/lorenzetti:latest
      volumes: 
        - ${{env.working-directory }}/volume:/volume
      env: 
        VOLUME: /volume
    steps:
      - name: Workdir
        shell: bash
        run: |
          cd $VOLUME
          rm -rf *
          git clone https://github.com/lorenzetti-hep/lorenzetti.git
          source lorenzetti/tests/workdir.sh
          ls -lisah
          pwd

  build:
    runs-on: self-hosted
    needs: workdir
    container:
      image: docker://lorenzetti/lorenzetti:latest
      volumes: 
        - ${{env.working-directory }}/volume:/volume
      env: 
        VOLUME: /volume
    steps:
      - name: Compile
        shell: bash
        working-directory: ${VOLUME}/lorenzetti
        run: |
          cd $VOLUME
          ls -lisah
          source /setup_envs.sh
          mkdir build && cd build && cmake .. && make -j8
          source setup.sh



              
