name: tests

on: [push]

jobs:

  workdir:
    runs-on: self-hosted
    container:
      image: docker://lorenzetti/lorenzetti:latest
      volumes: 
        - volume:/volume

    steps:
      - name: Workdir
        shell: bash
        run: |
          cd /volume && rm -rf *
          git clone https://github.com/lorenzetti-hep/lorenzetti.git
          source lorenzetti/tests/workdir.sh

  build:
    runs-on: self-hosted
    needs: workdir
    container:
      image: docker://lorenzetti/lorenzetti:latest
      volumes: 
        - volume:/volume
    steps:
      - name: Compile
        shell: bash
        run: |
          source /setup_envs.sh && cd /volume 
          cd lorenzetti && mkdir build && cd build
          cmake .. && make -j8
          cd .. && source setup.sh
          
  generation:
    runs-on: self-hosted
    needs: build
    container:
      image: docker://lorenzetti/lorenzetti:latest
      volumes: 
        - volume:/volume
    steps:
      - name: Generation
        shell: bash
        run: |
          source /setup_envs.sh && cd /volume/lorenzetti && source setup.sh
          source tests/gen_main.sh
        
          
              
