name: tests

on: [push]

jobs:

  workdir:
    runs-on: self-hosted
    container:
      image: docker://lorenzetti/lorenzetti:latest
    steps:
      - name: Workdir
        shell: bash
        run: |
          pwd
          ls -lisah
          rm -rf *
          touch x.sh
          git clone https://github.com/lorenzetti-hep/lorenzetti.git
          source lorenzetti/tests/workdir.sh
          ls -lisah
          pwd

  build:
    runs-on: self-hosted
    needs: workdir
    container:
      image: docker://lorenzetti/lorenzetti:latest
    steps:
      - name: Compile
        shell: bash
        run: |
          ls -lisah
          touch y.sh




              
