name: tests

on: [push]

jobs:

  workdir:
    runs-on: self-hosted
    container:
      image: docker://lorenzetti/lorenzetti:latest
    steps:
      - name: Workdir
        shell: bash
        run: |
          rm -rf *
          git clone https://github.com/lorenzetti-hep/lorenzetti.git

  build:
    runs-on: self-hosted
    needs: workdir
    container:
      image: docker://lorenzetti/lorenzetti:latest
    steps:
      - name: Compile
        shell: bash
        run: |
          ls -lisah
          cd lorenzetti && mkdir build && cd build && cmake .. && make -j4 && cd ..
          source setup.sh




              
